import './globals.css';

export const metadata = {
  title: 'Next.js with tailwindcss',
  description: 'Generated by @alexandrearaujoo'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
